### ISSUE TITLE
Increased definition of location code usage

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#2]
A comment at the 2019 FDSN meeting was that a location code convention or more strict guidelines were needed.  When use cases were summarized it was unclear what the best commonality was given the variety.

This could use further consideration.

**Comment by crotwell** [comment]
In general I don't think there is sufficient agreement to establish much of a convention at this point.

Perhaps suggestions that:

1. channels from the same instrument that differ only in orientation or sampling rate, like B_H_N and B_H_E or L_H_Z and S_H_Z, have the same location code
2. the primary seismic channels at traditional seismic stations should have location code 00, or an empty location code
3. channels that should go together should have the same location code
4. otherwise up to the network to decide on the meaning of the location code

**Comment by chad-earthscope** [comment]
I agree.  With no stricter convention on the table to consider and some degree of consensus a good fall back is a list of guidelines.

I would add a suggestion for arrays of sensors:

5. logically group sensors in an array in a regular, systematic scheme, e.g. incrementing numbers for a linear array.

**Comment by flofux** [comment]
> In general I don't think there is sufficient agreement to establish much of a convention at this point.
> 
> Perhaps suggestions that:
> 
> 1. channels from the same instrument that differ only in orientation or sampling rate, like B_H_N and B_H_E or L_H_Z and S_H_Z, have the same location code
> 2. the primary seismic channels at traditional seismic stations should have location code 00, or an empty location code
> 3. channels that should go together should have the same location code
> 4. otherwise up to the network to decide on the meaning of the location code

I fully support this.

**Comment by WayneCrawford** [comment]
One comment: in OBS data we have to distinguish between data with a "drifting" clock and the corrected data.  We have decided for the moment to use the Data Quality Code, although it is invisible "from the outside".  John Clinton suggested using a different location code (i.e. 00+ for uncorrected, 50+ for corrected) but this seemed a bit arbitrary and could be "overwritten" by other needs for location codes.

What I'm getting at is: maybe one could suggest that the part of location codes beyond 2-digits could be used for non-location-specific information?  I know I'm throwing a curveball very late in the game, my apologies.

**Comment by crotwell** [comment]
Another option, now that channel codes are expanded from 3 chars, would be to create a new source code that was for the non-corrected data. It would have to be 2 chars, but this type of idea is exactly why we need an expanded and more flexible channel identifier. 

For example the FDSN could define the source code "HU" to be for an "uncorrected time" seismometer channel, and you could continue to use H for the corrected version.

**Comment by crotwell** [comment]
Proposal, add to "Location code usage" section. I embellished the above items a bit, adding 2, 4 and 6.


The use and meaning of the location code is generally up to the defining network. However the following guidelines are recommended for consistency across networks:

1.   Channels that are closely related should have the same location code, e.g. channels from the same instrument that differ only in orientation or sampling rate, like B_H_Z and B_H_E or B_H_Z and S_H_Z, should have the same location code.
2. Sharing a single location code does not necessarily imply the channels come from the same instrument, e.g. the primary seismometer and primary accelerometer might both have location code '00' even if they are physically separate instruments.
3.  The primary seismic channels at traditional seismic stations should have location code of 00 or be empty. 
4.  Use of an empty location code is recommended only for stations that do not have multiple instruments of the same type and have traditionally not used location codes.
5.  Sensors in an array within a station may be logically grouped in a regular, systematic scheme, e.g. incrementing numbers for a linear array, or using two identifiers separated by a dash for a 2D grid.
6. Alphabetical ordering should be considered desirable, e.g. using '01' to '10' instead of '1' to '10' for a linear array. 
7.  Otherwise the network may use the location code for any meaningful system of organizing and namespacing channels at a station.

**Comment by chad-earthscope** [comment]
Added in e5d4f5cd66eb8490c1cc760c05f42c62e1d99aa1

**Comment by crotwell** [comment]
Know this issue is already closed, but found this info on loc code usage in old IRIS newsletter, so just adding for documentation purposes:

[IRIS newsletter vol 1 no 1](https://ds.iris.edu/ds/newsletter/vol1/no1/1/specification-of-seismograms-the-location-identifier/)
