### ISSUE TITLE
Sample rates above 5000 sps? 

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/source-identifiers#23]
Should sample rates above 5000 sps be allowed?  I can imagine that we will get there some day.

Also, while I'm on the subject (but not ready for a different "issue" because maybe we already discussed this), should the sampling rate be expressed in "Hz" (as it is currently), or in "sps".  Hertz is defined as "cycles per second" and sampling is not a cycle.  In my opinion this leads to confusion as people see a "100 Hz" instrument and think it might be able to study signals out to 100 Hz, whereas with "100 sps" this ambiguity disappears.

**Comment by chad-earthscope** [comment]
> Should sample rates above 5000 sps be allowed? I can imagine that we will get there some day.

Yes, how about an `J` code for sps > 5000 and no "lower bound" defined, so without two bands like the other paired high rates?

> Also, while I'm on the subject (but not ready for a different "issue" because maybe we already discussed this), should the sampling rate be expressed in "Hz" (as it is currently), or in "sps". 

Huh, I've always seen it used interchangeably as described here:
https://en.wikipedia.org/wiki/Sampling_(signal_processing)#:~:text=A%20commonly%20seen%20unit%20of,is%2048%2C000%20samples%20per%20second.

But clearer is better, so I'm all for sps.  Mind if I use "Samples per second" or "Samples/second" instead of "sps" for even more clarity?

**Comment by crotwell** [comment]
+1 on J for >5000

Ambivalent on Hz vs sps, but if so spelling it out is good.

Currently, at least in my browser, the lower bound col has heading `Lower bound (se` so think we might have run out of horizontal space.

Maybe it is worth splitting the sample rate col into 2 cols so easier to read?
