### ISSUE TITLE
Mark O-band usage as deprecated

### ISSUE THREAD

**Issue by chad-earthscope** [FDSN/source-identifiers#27]
The "O" channel band is for "Opaque channel".  I propose marking/describing this band as deprecated or strongly discouraged from use.  Except for short-term, in-house use of data, opaque data is essentially worthless and doomed to be unreadable in the future.

For operational network needs of state-of-health, etc. there is already an "A" - Administrative channel, which is where opaque data can be justified.

**Comment by crotwell** [comment]
+1 especially now that new instrument codes can be defined...

**Comment by WayneCrawford** [comment]
+1 especially since I wasted a huge amount of time once trying to figure out how to put all the supplementary info in these blockettes before figuring out that there were many better ways to save this info!

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 4 September 2020 at 23:41:35, Philip Crotwell (notifications@github.com) wrote:

+1 especially now that new instrument codes can be defined...

**Comment by crotwell** [comment]
Just a thought, but the O band code can be seen as a very different thing from using an Opaque Data blockette (2000). 

Is it worth keeping O, but redefining it to be an "irregularly sampled" channel instead of opaque? Opaque really has nothing to do with the band. 

I am thinking of cases where there could be a channel source defined for something such as a trigger, that emits effectively one sample (the trigger) at irregular times. But it would still need a band code, and A seems wrong.

Not really sure this is needed, but maybe the concept of a channel that is irregular is worth thinking about.

**Comment by crotwell** [comment]
Or deprecate "O", but add an "I" band code for "Irregularly sampled"?

**Comment by crotwell** [comment]
Thinking more, I feel like if O is going to be deprecated, then A should be deprecated as well. Both were source codes masquerading as band codes. 

A band code to represent irregularly sampled data might still be useful. I suppose it could be A or O, or a new letter like I, but it should be a band code, eg relates only to sampling rate, not a source code in the band code position.

**Comment by chad-earthscope** [comment]
Agreed, I think the `O` band is not directly related to B2000 usage in that they can be used independently.  

> Or deprecate "O", but add an "I" band code for "Irregularly sampled"?

Seems OK to me.

> Thinking more, I feel like if O is going to be deprecated, then A should be deprecated as well. Both were source codes masquerading as band codes.

Indeed.   OTOH, the advantage of A as a band code is to allow the originator to define the source, which, for odd-ball state-of-health channels, may be more reasonable than requiring source codes to be defined.  Alternatively we have a source code allowing arbitrary additions.

The portable WG is working on standard state-of-heath definitions and we should eventually assign some channel codes to them, but we'll never be able to define them all and we need some reasonable way to allow new SOH channels to be constructed.

**Comment by crotwell** [comment]
Everything will get easier once the source code expands beyond 1 char for sure.

The big disadvantage imho of A as a band code is that you loose any information about the actual band, and lots of soh channels are regularly sampled. 

If odd-ball soh channels are a concern that could be soved with A as a band code, it seems like they could also be fixed with multichar subsource codes. So if "SH" was a generic state of health source code, then you could have L_SH_ODD for some odd ball channel. Feels much more informative than A_H_C where the H is not the same as a H source code as in L_H_Z.

This was kind of my argument for leaving the Y code in as a "user defined, unregistered" source. Then the 3 char subsource code can be used however is needed without having to "define them all". I am not sure if Y is the right way, but keeping band and source information separate seems well worth it to me. 

I guess I feel that A and O as band codes are as or more deserving of deprecation than X and Y as source codes.

**Comment by chad-earthscope** [comment]
> If odd-ball soh channels are a concern that could be soved with A as a band code, it seems like they could also be fixed with multichar subsource codes. So if "SH" was a generic state of health source code, then you could have L_SH_ODD for some odd ball channel. Feels much more informative than A_H_C where the H is not the same as a H source code as in L_H_Z.

This argument for regularized usage of the fields is compelling, I'm in for deprecating both `A` and `O`.  The only downside I see is that a pickup in usage for multicharacter sources will not happen until the new identifiers are supported by formats.

I suggest that we also designate such a state of health source code, `SH` is OK.  We know that an effort is underway to create standardized state of health channel definitions and there will need to be codes for them.  I think we may want these in separate source codes, alternatively as a pattern of subsource codes.  This topic deserves a new issue.

**Comment by chad-earthscope** [comment]
OK, Added the `I` and deprecated the `A` and `O` band codes:
http://docs.fdsn.org/projects/source-identifiers/en/draft/channel-codes.html#band-code

Please make sure that's in the report.
